version: "3.9"

networks:
  bigdata: {}

volumes:
  hadoop_namenode:
  hadoop_datanode:
  databend_meta:
  databend_query:

services:
  # ---------- Hadoop (HDFS 3.2.1) ----------
  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8   # ← fixed tag
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=demo
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks: [bigdata]

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8   # ← fixed tag
    container_name: datanode
    hostname: datanode
    depends_on: [hadoop-namenode]
    environment:
      - CLUSTER_NAME=demo
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - DFS_CONF_dfs_replication=1
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks: [bigdata]

  # ---------- ZooKeeper & Kafka ----------
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports: ["2181:2181"]
    networks: [bigdata]

  kafka:
    image: bitnami/kafka:3.7.0          # verified tag :contentReference[oaicite:1]{index=1}
    container_name: kafka
    depends_on: [zookeeper]
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports: ["9092:9092"]
    networks: [bigdata]

  # ---------- Databend ----------
# --- only the Databend section changed ----------
  databend-meta:
    image: datafuselabs/databend-meta:v1.2.657-nightly   # ← new tag
    container_name: databend-meta
    command: ["databend-meta","--log-level=INFO","--single"]
    volumes:
      - databend_meta:/var/lib/databend
    ports:
      - "9191:9191"        # gRPC / admin
    networks: [bigdata]

  databend-query:
    image: datafuselabs/databend-query:v1.2.657-nightly  # ← new tag
    container_name: databend-query
    depends_on: [databend-meta]
    command: ["databend-query","--log-level=INFO","--meta-addr=databend-meta:9191"]
    volumes:
      - databend_query:/var/lib/databend
    ports:
      - "8000:8000"        # HTTP SQL console
      - "3307:3307"        # MySQL wire-protocol
    networks: [bigdata]
# -------------------------------------------------------


  # ---------- Spark ----------
  spark-master:
    image: bitnami/spark:3.5.0
    container_name: spark-master
    hostname: spark-master
    environment: [SPARK_MODE=master]
    ports:
      - "7077:7077"
      - "8080:8080"
    networks: [bigdata]

  spark-worker:
    image: bitnami/spark:3.5.0
    container_name: spark-worker
    depends_on: [spark-master]
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    ports: ["8081:8081"]
    networks: [bigdata]
